server:
  servlet:
    contextPath: /api
  port: 8200
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/test
  liquibase:
    change-log: classpath:/changelog/changelog-master.yaml
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG
        web: debug
